import { StyleSheet } from 'react-native';

const InventoryStyles = StyleSheet.create({
    container: {
        height: '100%',
        width: '100%',
    },
    headerContent: {
        height: '10%',
        width: '100%',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'column',
    },
    content: {
        height: '60%',
        paddingTop: 32,
        display: 'flex',
        flexDirection: 'column',
        width: '100%',
        alignItems: 'center',
    },
    footerContent: {
        width: '100%',
        height: '20%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-evenly',
        alignItems: 'center',
    },
    headerText: {
        fontWeight: 'bold',
    },
    emptyContainer: {
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
        paddingHorizontal: '5%',
    },
    subHeader: {
        fontWeight: 'bold',
        marginBottom: 12,
    },
    button: {
        width: '90%',
        backgroundColor: '#457EAC',

        fontSize: 20,
        padding: '5%',
        borderRadius: 15,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        textAlign: 'center',
        marginVertical: '1%',
        // Shadow for iOS
        shadowColor: 'black',
        shadowOffset: { width: 5, height: 2 },
        shadowOpacity: 0.4,
        shadowRadius: 5,
        // Shadow for Android
        elevation: 5,
        margin: 'auto',
    },
    folderButton: {
        height: 100,
        maxHeight: 350,
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    locationDetailsButton: {
        height: 200,
        maxHeight: 350,
    },
    locationDetailsButtonInternal: {
        display: 'flex',
        justifyContent: 'flex-start',
        alignItems: 'center',
        //backgroundColor: 'red',
        alignSelf: 'center',
        width: '100%',
        height: '100%',
        flexDirection: 'row',
        flexGrow: 2,
    },
    buttonText: {
        fontSize: 18,
        color: 'white',
        width: '100%',
    },
    locationDetailsButtonTitle: {
        display: 'flex',
        fontSize: 22,
        fontWeight: 'bold',
        marginBottom: 4,
        flexWrap: 'wrap',
    },
    locationDetailsButtonSubtitle: {
        fontWeight: 'bold',
    },
    list: {
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
    },
    listItem: {
        height: 75,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
        paddingHorizontal: '10%',
        borderBottomWidth: 1,
        borderBottomColor: 'gray',
        backgroundColor: 'red',
    },
    productIconContainer: {
        //backgroundColor: 'purple',
        width: '25%',
        height: '100%',
    },
    productIcon: {
        objectFit: 'contain',
        width: '100%',
        height: '100%',
    },
    loggedItemDetailsContainer: {
        flexGrow: 2,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        paddingLeft: 12,
    },
    loggedItemDetailsSection: {
        marginBottom: 4,
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
    },
    textInput: {
        width: '80%',
        backgroundColor: '#fff',
        paddingHorizontal: 15,
        paddingVertical: 12,
        borderRadius: 10,
        fontSize: 16,
        borderWidth: 1,
        borderColor: '#ddd',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3, // Android shadow
    },
});
export default InventoryStyles;
